#!/bin/bash
set -e
shopt -s extglob

run_backend() {
  cd /workspace
  source /workspace/.venv/bin/activate
  # echo "Migration started..."
  # alembic -c src/backend/alembic.ini upgrade head
  # echo "Migration finished..."
  echo "Starting FastAPI..."
  exec uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000 --loop asyncio
}

run_frontend() {
  cd /workspace/src/frontend
  echo "Starting Frontend..."
  pm2 start npm -- start
  echo "Frontend started..."
}
